import json, csv

scholarships = [
  {
    "title": {"en": "Chevening Scholarship 2027/2028", "ar": "منحة تشيفينيج 2027/2028"},
    "description": {"en": "The UK government prestigious global scholarship programme. Chevening offers full funding for outstanding professionals with leadership potential to pursue a one-year masters degree at any UK university. Covers tuition, living allowance, travel and accommodation.", "ar": "برنامج المنح الدراسية العالمي المرموق للحكومة البريطانية. تقدم منحة تشيفينيج تمويلاً كاملاً للمهنيين المتميزين ذوي الإمكانات القيادية لمتابعة درجة الماجستير في أي جامعة بريطانية."},
    "country": {"en": "United Kingdom", "ar": "المملكة المتحدة"},
    "university": {"en": "Any UK University", "ar": "أي جامعة بريطانية"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Leadership", "Public Policy", "International Relations"],
    "deadline": "2026-10-06",
    "link": "https://www.chevening.org/apply/",
    "image": "https://images.unsplash.com/photo-1526129318478-62ed807ebdf9?q=80&w=800&auto=format&fit=crop",
    "keywords": ["UK", "United Kingdom", "British", "Chevening", "Master", "Leadership", "Fully Funded", "Government"],
    "status": "approved"
  },
  {
    "title": {"en": "Gates Cambridge Scholarship 2027", "ar": "منحة غيتس كامبريدج 2027"},
    "description": {"en": "One of the worlds most prestigious fully funded scholarships, awarded by the Bill and Melinda Gates Foundation to outstanding applicants from outside the UK to pursue a postgraduate degree at the University of Cambridge.", "ar": "واحدة من أرقى المنح الدراسية الممولة بالكامل في العالم، تمنح لمتقدمين متميزين من خارج المملكة المتحدة لمتابعة درجة الدراسات العليا في جامعة كامبريدج."},
    "country": {"en": "United Kingdom", "ar": "المملكة المتحدة"},
    "university": {"en": "University of Cambridge", "ar": "جامعة كامبريدج"},
    "degree": "PhD", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Science", "Technology", "Arts", "Social Sciences"],
    "deadline": "2027-01-07",
    "link": "https://www.gatescambridge.org/",
    "image": "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Cambridge", "Gates", "UK", "PhD", "Master", "Fully Funded", "Prestigious"],
    "status": "approved"
  },
  {
    "title": {"en": "Rhodes Scholarship at University of Oxford", "ar": "منحة رودس في جامعة أكسفورد"},
    "description": {"en": "The Rhodes Scholarship is the oldest and most celebrated international fellowship award in the world enabling exceptional students to study at the University of Oxford. Covers all tuition fees, living stipend, health insurance, and travel.", "ar": "منحة رودس هي أقدم وأشهر جائزة زمالة دولية في العالم وتمكن الطلاب الاستثنائيين من الدراسة في جامعة أكسفورد. تغطي جميع الرسوم الدراسية ومخصصات المعيشة والتأمين والسفر."},
    "country": {"en": "United Kingdom", "ar": "المملكة المتحدة"},
    "university": {"en": "University of Oxford", "ar": "جامعة أكسفورد"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Law", "Politics", "Medicine", "Sciences"],
    "deadline": "2026-10-01",
    "link": "https://www.rhodeshouse.ox.ac.uk/scholarships/apply/",
    "image": "https://images.unsplash.com/photo-1580800434132-15b9dfb53cfe?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Oxford", "Rhodes", "UK", "Master", "Fully Funded", "Prestigious", "Leadership"],
    "status": "approved"
  },
  {
    "title": {"en": "DAAD Scholarship Development-Related Postgraduate Courses", "ar": "منحة DAAD للدراسات العليا المتعلقة بالتنمية"},
    "description": {"en": "DAAD German Academic Exchange Service funds international students from developing countries to pursue masters degrees at German universities in fields relevant to sustainable development. Covers full tuition, monthly stipend, health insurance, and airfare.", "ar": "يموّل برنامج DAAD الطلاب الدوليين من الدول النامية لمتابعة درجات الماجستير في الجامعات الألمانية في مجالات التنمية المستدامة. يغطي الرسوم والراتب والتأمين والأجرة الجوية."},
    "country": {"en": "Germany", "ar": "ألمانيا"},
    "university": {"en": "Various German Universities", "ar": "جامعات ألمانية مختلفة"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Development Studies", "Environmental Science", "Agriculture", "Engineering", "Public Health"],
    "deadline": "2026-10-31",
    "link": "https://www.daad.de/en/studying-in-germany/scholarships/scholarship-database/",
    "image": "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Germany", "DAAD", "German", "Master", "Fully Funded", "Development", "Sustainable"],
    "status": "approved"
  },
  {
    "title": {"en": "Fulbright Foreign Student Program", "ar": "برنامج فولبرايت للطلاب الأجانب"},
    "description": {"en": "The Fulbright Program is the US governments flagship international educational exchange program. Offers full funding for international students to study for a masters or PhD degree at a US university. Covers tuition, living expenses, health insurance, and travel.", "ar": "برنامج فولبرايت هو البرنامج الرائد للتبادل التعليمي الدولي للحكومة الأمريكية. يقدم تمويلاً كاملاً للطلاب الدوليين لدراسة الماجستير أو الدكتوراه في جامعة أمريكية."},
    "country": {"en": "United States", "ar": "الولايات المتحدة الأمريكية"},
    "university": {"en": "Various US Universities", "ar": "جامعات أمريكية مختلفة"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Arts", "Sciences", "Engineering", "Social Sciences", "Business"],
    "deadline": "2026-09-30",
    "link": "https://foreign.fulbrightonline.org/",
    "image": "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=800&auto=format&fit=crop",
    "keywords": ["USA", "America", "Fulbright", "Master", "PhD", "Fully Funded", "Government"],
    "status": "approved"
  },
  {
    "title": {"en": "Erasmus Mundus Joint Masters Scholarship", "ar": "منحة إيراسموس موندوس للماجستير المشترك"},
    "description": {"en": "Erasmus Mundus Joint Masters is a prestigious integrated international study program jointly delivered by an international consortium of higher education institutions. Scholarships cover tuition fees, travel costs, and monthly living allowance.", "ar": "برنامج إيراسموس موندوس للماجستير المشترك هو برنامج دراسي دولي متكامل ومرموق يقدمه اتحاد دولي من مؤسسات التعليم العالي. تغطي المنح الرسوم والسفر وبدل المعيشة."},
    "country": {"en": "Europe", "ar": "أوروبا"},
    "university": {"en": "Multiple European Universities", "ar": "جامعات أوروبية متعددة"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Engineering", "Arts", "Sciences", "Humanities"],
    "deadline": "2027-01-15",
    "link": "https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en",
    "image": "https://images.unsplash.com/photo-1543722530-d2c3201371e7?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Europe", "Erasmus", "Mundus", "Master", "Fully Funded", "EU", "Multi-Country"],
    "status": "approved"
  },
  {
    "title": {"en": "MEXT Japanese Government Scholarship", "ar": "منحة الحكومة اليابانية MEXT"},
    "description": {"en": "The Japanese Government MEXT Scholarship provides full funding for international students to study at Japanese universities at the masters and doctoral levels including Japanese language training.", "ar": "توفر منحة الحكومة اليابانية MEXT تمويلاً كاملاً للطلاب الدوليين للدراسة في الجامعات اليابانية على مستوى الماجستير والدكتوراه بما في ذلك تدريب اللغة اليابانية."},
    "country": {"en": "Japan", "ar": "اليابان"},
    "university": {"en": "Various Japanese Universities", "ar": "جامعات يابانية مختلفة"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Engineering", "Science", "Technology", "Humanities", "Social Sciences", "Agriculture"],
    "deadline": "2027-01-31",
    "link": "https://www.studyinjapan.go.jp/en/smap-stopj-applications-research.html",
    "image": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Japan", "MEXT", "Japanese", "Master", "PhD", "Fully Funded", "Government", "Tokyo"],
    "status": "approved"
  },
  {
    "title": {"en": "Global Korea Scholarship GKS KGSP", "ar": "منحة كوريا العالمية GKS"},
    "description": {"en": "The Global Korea Scholarship GKS also known as the Korean Government Scholarship Program KGSP is a fully funded scholarship from the South Korean government for international students. Covers tuition, living stipend, airfare, and Korean language training.", "ar": "منحة كوريا العالمية GKS المعروفة ببرنامج المنح الحكومية الكورية KGSP برنامج منح ممول بالكامل من الحكومة الكورية الجنوبية للطلاب الدوليين."},
    "country": {"en": "South Korea", "ar": "كوريا الجنوبية"},
    "university": {"en": "Various Korean Universities", "ar": "جامعات كورية مختلفة"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Engineering", "IT", "Business", "Sciences", "Humanities"],
    "deadline": "2027-03-01",
    "link": "https://www.gksscholarship.com/",
    "image": "https://images.unsplash.com/photo-1538485399081-7191377e8241?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Korea", "South Korea", "GKS", "KGSP", "Master", "PhD", "Fully Funded", "Korean"],
    "status": "approved"
  },
  {
    "title": {"en": "Swedish Institute Scholarship for Global Professionals", "ar": "منحة المعهد السويدي للمهنيين العالميين"},
    "description": {"en": "The Swedish Institute offers scholarships for international students from eligible countries to pursue full-time masters studies in Sweden. Covers tuition fees, living expenses, travel grant, and insurance.", "ar": "يقدم المعهد السويدي منحاً دراسية للطلاب الدوليين من الدول المؤهلة لمتابعة دراسات الماجستير بدوام كامل في السويد. تغطي الرسوم والمعيشة ومنحة السفر والتأمين."},
    "country": {"en": "Sweden", "ar": "السويد"},
    "university": {"en": "Swedish Universities", "ar": "الجامعات السويدية"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Sustainability", "Technology", "Social Sciences", "Business"],
    "deadline": "2027-02-10",
    "link": "https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/",
    "image": "https://images.unsplash.com/photo-1508817628294-5a453fa0b8fb?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Sweden", "Swedish", "SI Scholarship", "Master", "Fully Funded", "Scandinavia", "Nordic"],
    "status": "approved"
  },
  {
    "title": {"en": "Australia Awards Scholarships", "ar": "منح جوائز أستراليا"},
    "description": {"en": "Australia Awards Scholarships are funded by the Australian Government providing opportunities for people from eligible countries to undertake full-time undergraduate or postgraduate study at Australian universities. Covers tuition, travel, living allowance, and health.", "ar": "منح جوائز أستراليا ممولة من الحكومة الأسترالية توفر فرصاً للأفراد من الدول المؤهلة لمتابعة الدراسة في الجامعات الأسترالية. تغطي الرسوم والسفر والمعيشة والصحة."},
    "country": {"en": "Australia", "ar": "أستراليا"},
    "university": {"en": "Australian Universities", "ar": "الجامعات الأسترالية"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Development", "Agriculture", "Health", "Education"],
    "deadline": "2026-04-30",
    "link": "https://www.australiaawards.gov.au/",
    "image": "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Australia", "Australian", "Australia Awards", "Master", "Fully Funded", "Government", "Development"],
    "status": "approved"
  },
  {
    "title": {"en": "Commonwealth Scholarship UK Masters and PhD", "ar": "منحة الكومنولث المملكة المتحدة"},
    "description": {"en": "Commonwealth Scholarships funded by the UK Foreign Commonwealth and Development Office FCDO enable talented students from Commonwealth countries to pursue postgraduate study at UK universities fully funded.", "ar": "منح الكومنولث ممولة من مكتب الشؤون الخارجية البريطاني وتمكن الطلاب الموهوبين من دول الكومنولث من متابعة الدراسات العليا في الجامعات البريطانية بتمويل كامل."},
    "country": {"en": "United Kingdom", "ar": "المملكة المتحدة"},
    "university": {"en": "UK Universities", "ar": "الجامعات البريطانية"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "STEM", "Business", "Social Sciences", "Public Health"],
    "deadline": "2026-10-22",
    "link": "https://cscuk.fcdo.gov.uk/scholarships/",
    "image": "https://images.unsplash.com/photo-1573503814083-b89d5ac83e0d?q=80&w=800&auto=format&fit=crop",
    "keywords": ["UK", "Commonwealth", "British", "Master", "PhD", "Fully Funded", "FCDO"],
    "status": "approved"
  },
  {
    "title": {"en": "Vanier Canada Graduate Scholarship PhD", "ar": "منحة فانييه كندا للخريجين"},
    "description": {"en": "The Vanier Canada Graduate Scholarships program attracts world-class doctoral students. Awards CAD 50000 per year for 3 years for PhD studies across health sciences, natural sciences, engineering, and social sciences.", "ar": "يهدف برنامج منح فانييه كندا إلى استقطاب طلاب الدكتوراه ذوي المستوى العالمي. يمنح 50000 دولار كندي سنوياً لمدة 3 سنوات لدراسات الدكتوراه."},
    "country": {"en": "Canada", "ar": "كندا"},
    "university": {"en": "Canadian Universities", "ar": "الجامعات الكندية"},
    "degree": "PhD", "fundingType": "Fully Funded",
    "majors": ["Health Sciences", "Natural Sciences", "Engineering", "Social Sciences", "Humanities"],
    "deadline": "2026-11-01",
    "link": "https://vanier.gc.ca/en/home-accueil.html",
    "image": "https://images.unsplash.com/photo-1517935706615-2717063c2225?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Canada", "Vanier", "Canadian", "PhD", "Fully Funded", "Research", "Graduate"],
    "status": "approved"
  },
  {
    "title": {"en": "SINGA Scholarship Singapore PhD", "ar": "منحة SINGA سنغافورة للدكتوراه"},
    "description": {"en": "The Singapore International Graduate Award SINGA is for international students pursuing a PhD at Singapore top research institutes including A*STAR NUS NTU and SUTD. Fully funded with monthly stipend airfare and allowance.", "ar": "جائزة سنغافورة الدولية للخريجين SINGA للطلاب الدوليين الذين يسعون للدكتوراه في أفضل معاهد البحث في سنغافورة. ممولة بالكامل مع راتب شهري وأجرة جوية."},
    "country": {"en": "Singapore", "ar": "سنغافورة"},
    "university": {"en": "NUS NTU A*STAR SUTD Singapore", "ar": "NUS / NTU / A*STAR / SUTD سنغافورة"},
    "degree": "PhD", "fundingType": "Fully Funded",
    "majors": ["Science", "Engineering", "Technology", "Biomedical Sciences", "Computing"],
    "deadline": "2027-01-01",
    "link": "https://www.singa.a-star.edu.sg/",
    "image": "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Singapore", "SINGA", "NUS", "NTU", "PhD", "Fully Funded", "Research", "STEM"],
    "status": "approved"
  },
  {
    "title": {"en": "ETH Zurich Excellence Scholarship Switzerland", "ar": "منحة التميز في ETH زيورخ سويسرا"},
    "description": {"en": "The Excellence Scholarship Opportunity Programme ESOP of ETH Zurich supports outstanding students pursuing a masters degree at one of the worlds top-ranked technical universities. Award covers tuition fees and monthly living stipend.", "ar": "يدعم برنامج ESOP في ETH زيورخ الطلاب المتميزين الراغبين في متابعة الماجستير في إحدى أعلى الجامعات التقنية مرتبةً في العالم. يغطي الرسوم الدراسية والراتب الشهري."},
    "country": {"en": "Switzerland", "ar": "سويسرا"},
    "university": {"en": "ETH Zurich", "ar": "جامعة ETH زيورخ"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Engineering", "Science", "Architecture", "Mathematics", "Computer Science"],
    "deadline": "2026-12-15",
    "link": "https://ethz.ch/en/studies/financial/scholarships/excellence-scholarship.html",
    "image": "https://images.unsplash.com/photo-1589519160732-576f165b9aad?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Switzerland", "ETH", "Zurich", "Master", "Fully Funded", "Engineering", "STEM"],
    "status": "approved"
  },
  {
    "title": {"en": "EPFL Excellence Fellowships Lausanne Switzerland", "ar": "زمالات التميز في EPFL لوزان سويسرا"},
    "description": {"en": "The EPFL Excellence Fellowships for outstanding students pursuing a masters degree at Ecole Polytechnique Federale de Lausanne consistently ranked among the worlds top universities. Covers tuition and monthly stipend.", "ar": "زمالات التميز في EPFL للطلاب المتميزين لمتابعة الماجستير في المدرسة البوليتكنيكية الفيدرالية في لوزان. تغطي الرسوم الدراسية والراتب الشهري."},
    "country": {"en": "Switzerland", "ar": "سويسرا"},
    "university": {"en": "EPFL Lausanne", "ar": "EPFL لوزان"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Engineering", "Computer Science", "Physics", "Mathematics", "Life Sciences"],
    "deadline": "2026-12-01",
    "link": "https://www.epfl.ch/education/master/master-in-engineering/excellence-fellowship/",
    "image": "https://images.unsplash.com/photo-1487958449943-2429e8be8625?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Switzerland", "EPFL", "Lausanne", "Master", "Fully Funded", "Engineering", "Science"],
    "status": "approved"
  },
  {
    "title": {"en": "Aga Khan Foundation International Scholarship", "ar": "منحة مؤسسة آغا خان الدولية"},
    "description": {"en": "The Aga Khan Foundation AKF offers scholarships for postgraduate study to outstanding students from developing countries who have no other means of financing their studies. Given as 50 percent grant and 50 percent loan.", "ar": "تقدم مؤسسة آغا خان AKF منحاً دراسية للدراسات العليا لطلاب متميزين من الدول النامية ليس لديهم وسائل أخرى لتمويل دراستهم. تمنح بنسبة 50 بالمئة منحة و50 بالمئة قرض."},
    "country": {"en": "Multiple Countries", "ar": "دول متعددة"},
    "university": {"en": "Top Universities Worldwide", "ar": "أفضل الجامعات في العالم"},
    "degree": "Master", "fundingType": "Partially Funded",
    "majors": ["Development", "Health", "Education", "Architecture", "Engineering"],
    "deadline": "2027-03-31",
    "link": "https://www.akdn.org/our-agencies/aga-khan-foundation/international-scholarship-programme",
    "image": "https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Aga Khan", "International", "Master", "Partially Funded", "Development", "Developing Countries"],
    "status": "approved"
  },
  {
    "title": {"en": "French Government Eiffel Excellence Scholarship", "ar": "منحة حكومة فرنسا إيفل للتميز"},
    "description": {"en": "The Eiffel Excellence Scholarship Programme managed by Campus France attracts top foreign students to masters and PhD programs at French higher education institutions. Covers monthly allowance, health insurance, and transportation.", "ar": "برنامج منحة التميز إيفل الذي تديره Campus France يستقطب أفضل الطلاب الأجانب في برامج الماجستير والدكتوراه في المؤسسات الفرنسية. يغطي البدل الشهري والتأمين والمواصلات."},
    "country": {"en": "France", "ar": "فرنسا"},
    "university": {"en": "French Universities", "ar": "الجامعات الفرنسية"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Engineering", "Law", "Economics", "Political Science", "Sciences", "Management"],
    "deadline": "2027-01-12",
    "link": "https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence",
    "image": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=800&auto=format&fit=crop",
    "keywords": ["France", "French", "Eiffel", "Master", "PhD", "Fully Funded", "Excellence", "Paris"],
    "status": "approved"
  },
  {
    "title": {"en": "Orange Knowledge Programme OKP Netherlands", "ar": "برنامج المعرفة البرتقالي هولندا"},
    "description": {"en": "The Orange Knowledge Programme OKP is the Netherlands Fellowship Programmes main scholarship for professionals from eligible countries to pursue a masters degree at a Dutch institution funded by the Dutch Ministry of Foreign Affairs.", "ar": "برنامج المعرفة البرتقالي OKP هو المنحة الرئيسية لبرامج الزمالة الهولندية للمهنيين من الدول المؤهلة لمتابعة الماجستير في مؤسسة هولندية."},
    "country": {"en": "Netherlands", "ar": "هولندا"},
    "university": {"en": "Dutch Institutions Wageningen Delft IHE", "ar": "المؤسسات الهولندية"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Agriculture", "Water Management", "Public Health", "Education", "Governance"],
    "deadline": "2027-02-28",
    "link": "https://www.studyinholland.nl/scholarships/highlighted-scholarships/orange-knowledge-programme",
    "image": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Netherlands", "Dutch", "OKP", "Orange Knowledge", "Master", "Fully Funded", "Holland"],
    "status": "approved"
  },
  {
    "title": {"en": "Rotary Peace Fellowship", "ar": "زمالة روتاري للسلام"},
    "description": {"en": "The Rotary Peace Fellowship supports individuals committed to promoting peace. Fellows study at one of six Rotary Peace Centers around the world pursuing a masters degree in peace and conflict resolution fully funded.", "ar": "تدعم زمالة روتاري للسلام الأفراد الملتزمين بتعزيز السلام. يدرس الزملاء في أحد مراكز روتاري للسلام الستة حول العالم لمتابعة ماجستير في دراسات السلام وحل النزاعات."},
    "country": {"en": "Multiple Countries", "ar": "دول متعددة"},
    "university": {"en": "Rotary Peace Centers Duke York Bradford Chulalongkorn", "ar": "مراكز روتاري للسلام"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Peace Studies", "International Relations", "Conflict Resolution", "Development"],
    "deadline": "2027-05-31",
    "link": "https://www.rotary.org/en/our-programs/peace-fellowships",
    "image": "https://images.unsplash.com/photo-1509358271058-acd22cc93898?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Rotary", "Peace", "Fellowship", "Master", "Fully Funded", "International", "Conflict Resolution"],
    "status": "approved"
  },
  {
    "title": {"en": "KAIST International Graduate Scholarship South Korea", "ar": "منحة KAIST الدولية للدراسات العليا كوريا"},
    "description": {"en": "KAIST Korea Advanced Institute of Science and Technology offers international graduate scholarships for outstanding students worldwide. Covers full tuition, monthly living allowance, and medical insurance for masters and PhD programs.", "ar": "تقدم KAIST معهد كوريا المتقدم للعلوم والتكنولوجيا منحاً دراسية للطلاب الدوليين المتميزين. تغطي الرسوم الكاملة والبدل الشهري والتأمين الطبي."},
    "country": {"en": "South Korea", "ar": "كوريا الجنوبية"},
    "university": {"en": "KAIST Korea Advanced Institute of Science and Technology", "ar": "معهد كوريا المتقدم للعلوم والتكنولوجيا KAIST"},
    "degree": "PhD", "fundingType": "Fully Funded",
    "majors": ["Computer Science", "Engineering", "Physics", "Chemistry", "Bioscience"],
    "deadline": "2027-03-15",
    "link": "https://admission.kaist.ac.kr/intl-graduate/",
    "image": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Korea", "KAIST", "South Korea", "PhD", "Master", "Fully Funded", "STEM", "Technology"],
    "status": "approved"
  },
  {
    "title": {"en": "KAUST Fellowship King Abdullah University Saudi Arabia", "ar": "زمالة جامعة الملك عبدالله KAUST السعودية"},
    "description": {"en": "The KAUST Fellowship provides a comprehensive financial package for graduate students including full tuition, monthly stipend, housing, medical coverage, and relocation allowance for MS and PhD programs in STEM fields.", "ar": "توفر زمالة KAUST حزمة مالية شاملة للطلاب تشمل الرسوم الكاملة والراتب الشهري والسكن والتغطية الطبية وبدل الانتقال لبرامج الماجستير والدكتوراه في STEM."},
    "country": {"en": "Saudi Arabia", "ar": "المملكة العربية السعودية"},
    "university": {"en": "KAUST King Abdullah University of Science and Technology", "ar": "جامعة الملك عبدالله للعلوم والتقنية KAUST"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Bioscience", "Engineering", "Computer Science", "Environmental Science", "Mathematics", "Physics"],
    "deadline": "2027-01-15",
    "link": "https://www.kaust.edu.sa/en/study/applying-to-kaust/tuition-fees-and-financial-assistance",
    "image": "https://images.unsplash.com/photo-1547481053-7d174f67b557?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Saudi Arabia", "KAUST", "Saudi", "Master", "PhD", "Fully Funded", "STEM", "Research"],
    "status": "approved"
  },
  {
    "title": {"en": "Stipendium Hungaricum Scholarship Hungary", "ar": "منحة Stipendium Hungaricum هنغاريا"},
    "description": {"en": "The Stipendium Hungaricum programme enables international students from partner countries to study in Hungary. The scholarship covers tuition fees, accommodation, a monthly stipend, and health insurance.", "ar": "برنامج Stipendium Hungaricum يمكن الطلاب الدوليين من الدول الشريكة من الدراسة في هنغاريا. يغطي الرسوم الدراسية والسكن والراتب الشهري والتأمين الصحي."},
    "country": {"en": "Hungary", "ar": "هنغاريا"},
    "university": {"en": "Hungarian Universities", "ar": "الجامعات الهنغارية"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Engineering", "Medicine", "Arts", "Sciences", "Business"],
    "deadline": "2027-01-15",
    "link": "https://stipendiumhungaricum.hu/",
    "image": "https://images.unsplash.com/photo-1576169342067-a06c41b30a34?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Hungary", "Hungarian", "Stipendium", "Master", "Bachelor", "PhD", "Fully Funded"],
    "status": "approved"
  },
  {
    "title": {"en": "Turkish Government Scholarship Turkiye Burslari", "ar": "منحة الحكومة التركية Turkiye Burslari"},
    "description": {"en": "Turkiye Scholarships is a government-funded program for international students at bachelor masters and PhD level. Covers full tuition accommodation monthly stipend health insurance Turkish language course and travel.", "ar": "برنامج منح تركيا هو برنامج منح ممول حكومياً للطلاب الدوليين. يغطي الرسوم الكاملة والسكن والراتب والتأمين ودورة اللغة التركية والسفر."},
    "country": {"en": "Turkey", "ar": "تركيا"},
    "university": {"en": "Turkish Universities", "ar": "الجامعات التركية"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Engineering", "Medicine", "Arts", "Social Sciences", "Agriculture"],
    "deadline": "2027-02-20",
    "link": "https://www.turkiyeburslari.gov.tr/en",
    "image": "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Turkey", "Turkish", "Turkiye", "Master", "Bachelor", "PhD", "Fully Funded", "Government"],
    "status": "approved"
  },
  {
    "title": {"en": "Chinese Government Scholarship CSC Program", "ar": "منحة الحكومة الصينية برنامج CSC"},
    "description": {"en": "The Chinese Government Scholarship administered by China Scholarship Council CSC funds international students to study at Chinese universities. Covers tuition accommodation stipend and health insurance for masters bachelor and PhD.", "ar": "تموّل منحة الحكومة الصينية التي يديرها مجلس المنح الصينية CSC الطلاب الدوليين للدراسة في الجامعات الصينية. تغطي الرسوم والسكن والراتب والتأمين."},
    "country": {"en": "China", "ar": "الصين"},
    "university": {"en": "Chinese Universities", "ar": "الجامعات الصينية"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Engineering", "Medicine", "Science", "Business", "Arts"],
    "deadline": "2027-04-30",
    "link": "https://www.campuschina.org/",
    "image": "https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?q=80&w=800&auto=format&fit=crop",
    "keywords": ["China", "Chinese", "CSC", "Master", "Bachelor", "PhD", "Fully Funded", "Beijing", "Shanghai"],
    "status": "approved"
  },
  {
    "title": {"en": "Stanford Knight-Hennessy Scholars Program", "ar": "برنامج ستانفورد للعلماء نايت-هينيسي"},
    "description": {"en": "One of the largest fully funded graduate fellowships in the world selecting up to 100 students annually to pursue any graduate degree at Stanford University with full financial support.", "ar": "أحد أكبر برامج الزمالة للدراسات العليا الممولة بالكامل في العالم. يختار ما يصل إلى 100 طالب سنوياً من جميع أنحاء العالم لمتابعة أي درجة دراسات عليا في جامعة ستانفورد."},
    "country": {"en": "United States", "ar": "الولايات المتحدة الأمريكية"},
    "university": {"en": "Stanford University", "ar": "جامعة ستانفورد"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Business", "Law", "Medicine", "Education", "Engineering"],
    "deadline": "2026-10-08",
    "link": "https://knight-hennessy.stanford.edu/",
    "image": "https://images.unsplash.com/photo-1564565694-4c0e62ea0c39?q=80&w=800&auto=format&fit=crop",
    "keywords": ["USA", "Stanford", "Knight-Hennessy", "Master", "PhD", "Fully Funded", "Prestigious", "Ivy"],
    "status": "approved"
  },
  {
    "title": {"en": "Harvard University GSAS Graduate Fellowship", "ar": "زمالة هارفارد للدراسات العليا"},
    "description": {"en": "Harvard University Griffin GSAS provides PhD students with multi-year funding packages including stipend health insurance and tuition covering 100 percent of demonstrated financial need for admitted graduate students.", "ar": "توفر كلية هارفارد للدراسات العليا Griffin GSAS لطلاب الدكتوراه حزم تمويل متعددة السنوات تشمل الراتب والتأمين الصحي والرسوم الدراسية."},
    "country": {"en": "United States", "ar": "الولايات المتحدة الأمريكية"},
    "university": {"en": "Harvard University", "ar": "جامعة هارفارد"},
    "degree": "PhD", "fundingType": "Fully Funded",
    "majors": ["Humanities", "Social Sciences", "Sciences", "Arts", "Engineering"],
    "deadline": "2026-12-01",
    "link": "https://gsas.harvard.edu/financial-support",
    "image": "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?q=80&w=800&auto=format&fit=crop",
    "keywords": ["USA", "Harvard", "PhD", "Fully Funded", "Prestigious", "Ivy League", "Research"],
    "status": "approved"
  },
  {
    "title": {"en": "NUS Research Scholarship Singapore", "ar": "منحة البحث في جامعة سنغافورة الوطنية NUS"},
    "description": {"en": "The National University of Singapore NUS offers Research Scholarships to outstanding graduate students for full-time research degree programs. Covers tuition fees and provides a monthly stipend. NUS is Asia top-ranked university.", "ar": "تقدم جامعة سنغافورة الوطنية NUS منحاً بحثية للطلاب المتميزين لبرامج درجات البحث بدوام كامل. تغطي الرسوم الدراسية وتوفر راتباً شهرياً. NUS هي الجامعة الأعلى تصنيفاً في آسيا."},
    "country": {"en": "Singapore", "ar": "سنغافورة"},
    "university": {"en": "National University of Singapore NUS", "ar": "جامعة سنغافورة الوطنية NUS"},
    "degree": "PhD", "fundingType": "Fully Funded",
    "majors": ["Engineering", "Computing", "Science", "Business", "Medicine", "Law"],
    "deadline": "2026-11-15",
    "link": "https://nusgs.nus.edu.sg/scholarships/",
    "image": "https://images.unsplash.com/photo-1571932090836-c8c555eb71e7?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Singapore", "NUS", "National University", "PhD", "Fully Funded", "Research", "Asia"],
    "status": "approved"
  },
  {
    "title": {"en": "University of Melbourne Graduate Research Scholarship", "ar": "منحة بحث الدراسات العليا في جامعة ملبورن"},
    "description": {"en": "The Melbourne Research Scholarship MRS includes an annual living allowance and tuition fee remission for PhD students pursuing research degrees at the University of Melbourne one of Australia leading universities.", "ar": "منحة البحث في ملبورن MRS تشمل بدل المعيشة السنوي والإعفاء من الرسوم الدراسية لطلاب الدكتوراه في جامعة ملبورن إحدى الجامعات الأسترالية الرائدة."},
    "country": {"en": "Australia", "ar": "أستراليا"},
    "university": {"en": "University of Melbourne", "ar": "جامعة ملبورن"},
    "degree": "PhD", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Science", "Arts", "Engineering", "Medicine", "Law"],
    "deadline": "2026-10-31",
    "link": "https://scholarships.unimelb.edu.au/awards/melbourne-research-scholarship",
    "image": "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Australia", "Melbourne", "PhD", "Fully Funded", "Research", "Australian"],
    "status": "approved"
  },
  {
    "title": {"en": "TU Delft Excellence Scholarship Netherlands", "ar": "منحة التميز في TU دلفت هولندا"},
    "description": {"en": "Delft University of Technology offers the TU Delft Excellence Scholarship for outstanding non-EEA masters students. Covers full tuition fees plus monthly living allowance for the entire two-year masters program duration.", "ar": "تقدم جامعة دلفت للتكنولوجيا منحة TU دلفت للتميز لطلاب الماجستير المتميزين من خارج المنطقة الاقتصادية الأوروبية. تغطي الرسوم الكاملة وبدل المعيشة الشهري."},
    "country": {"en": "Netherlands", "ar": "هولندا"},
    "university": {"en": "TU Delft Delft University of Technology", "ar": "جامعة دلفت للتكنولوجيا"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Engineering", "Architecture", "Technology", "Industrial Design", "Aerospace"],
    "deadline": "2027-02-01",
    "link": "https://www.tudelft.nl/en/education/practical-matters/scholarships/tu-delft-excellence-scholarships",
    "image": "https://images.unsplash.com/photo-1534430480872-3498386e7856?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Netherlands", "Delft", "TU Delft", "Master", "Fully Funded", "Engineering", "Technology"],
    "status": "approved"
  },
  {
    "title": {"en": "Italian Government Scholarship MAECI Program", "ar": "منحة الحكومة الإيطالية MAECI"},
    "description": {"en": "The Italian Government through the Ministry of Foreign Affairs and International Cooperation MAECI offers scholarships for foreign citizens to study in Italy. Covers accommodation living allowance and health insurance.", "ar": "تقدم الحكومة الإيطالية من خلال وزارة الخارجية MAECI منحاً دراسية للمواطنين الأجانب الراغبين في الدراسة في إيطاليا. تغطي السكن وبدل المعيشة والتأمين الصحي."},
    "country": {"en": "Italy", "ar": "إيطاليا"},
    "university": {"en": "Italian Universities", "ar": "الجامعات الإيطالية"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Arts", "Architecture", "Sciences", "Engineering", "Humanities", "Fashion Design"],
    "deadline": "2026-10-30",
    "link": "https://www.esteri.it/en/opportunities-and-resources/borse-di-studio/",
    "image": "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Italy", "Italian", "MAECI", "Master", "PhD", "Fully Funded", "Rome", "Milan"],
    "status": "approved"
  },
  {
    "title": {"en": "Cambridge Trust International Scholarship", "ar": "منحة Cambridge Trust الدولية"},
    "description": {"en": "Cambridge Trust awards scholarships to outstanding international applicants pursuing masters or doctoral degrees at the University of Cambridge. Available across all subjects and can cover tuition fees and maintenance costs.", "ar": "تمنح Cambridge Trust منحاً للمتقدمين الدوليين المتميزين الراغبين في متابعة الماجستير أو الدكتوراه في جامعة كامبريدج. متاحة في جميع التخصصات وتغطي الرسوم وتكاليف الصيانة."},
    "country": {"en": "United Kingdom", "ar": "المملكة المتحدة"},
    "university": {"en": "University of Cambridge", "ar": "جامعة كامبريدج"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Science", "Arts", "Law", "Engineering", "Medicine"],
    "deadline": "2026-12-05",
    "link": "https://www.cambridgetrust.org/",
    "image": "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Cambridge", "UK", "Master", "PhD", "Fully Funded", "Prestigious", "British"],
    "status": "approved"
  },
  {
    "title": {"en": "Imperial College London Presidents PhD Scholarships", "ar": "منح رئيس Imperial College للدكتوراه"},
    "description": {"en": "Imperial College London offers Presidents PhD Scholarships for doctoral research across all STEM disciplines. Provides full tuition fees annual stipend and research budget for three to four years of doctoral study.", "ar": "تقدم Imperial College London منح رئيس الجامعة للدكتوراه في جميع تخصصات STEM. توفر الرسوم الكاملة والراتب السنوي وميزانية البحث لثلاث إلى أربع سنوات."},
    "country": {"en": "United Kingdom", "ar": "المملكة المتحدة"},
    "university": {"en": "Imperial College London", "ar": "Imperial College London"},
    "degree": "PhD", "fundingType": "Fully Funded",
    "majors": ["Engineering", "Science", "Medicine", "Computing", "Mathematics", "Physics"],
    "deadline": "2027-01-08",
    "link": "https://www.imperial.ac.uk/study/fees-and-funding/president-phd-scholarships/",
    "image": "https://images.unsplash.com/photo-1601046668428-94ea13437736?q=80&w=800&auto=format&fit=crop",
    "keywords": ["UK", "Imperial", "London", "PhD", "Fully Funded", "STEM", "Research", "British"],
    "status": "approved"
  },
  {
    "title": {"en": "Leiden University Excellence Scholarship LExS Netherlands", "ar": "منحة تميز جامعة ليدن LExS هولندا"},
    "description": {"en": "Leiden University offers the Excellence Scholarship Programme LExS to the best non-EEA masters students. Three levels of awards 10000 EUR 15000 EUR or Full tuition plus 10000 EUR based on academic excellence.", "ar": "تقدم جامعة ليدن برنامج المنح الدراسية للتميز LExS لأفضل طلاب الماجستير من خارج المنطقة الاقتصادية الأوروبية. ثلاثة مستويات من الجوائز بناءً على التميز الأكاديمي."},
    "country": {"en": "Netherlands", "ar": "هولندا"},
    "university": {"en": "Leiden University", "ar": "جامعة ليدن"},
    "degree": "Master", "fundingType": "Partially Funded",
    "majors": ["All Fields", "Law", "Social Sciences", "Humanities", "Sciences", "Governance"],
    "deadline": "2027-02-01",
    "link": "https://www.universiteitleiden.nl/en/education/scholarships-and-grants/excellence-scholarship-programme",
    "image": "https://images.unsplash.com/photo-1537201327700-47d85b4fe5ce?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Netherlands", "Leiden", "Holland", "Master", "Excellence", "Partially Funded"],
    "status": "approved"
  },
  {
    "title": {"en": "NYU Abu Dhabi Presidential Fellowship UAE", "ar": "زمالة رئيس جامعة نيويورك أبوظبي الإمارات"},
    "description": {"en": "NYU Abu Dhabi offers Presidential Fellowships to exceptional graduate students accepted to PhD programs. Covers full tuition fees competitive monthly stipend housing travel and health coverage for the full degree duration.", "ar": "تقدم جامعة نيويورك أبوظبي زمالاتها الرئاسية لطلاب الدكتوراه الاستثنائيين المقبولين. تغطي الرسوم الكاملة والراتب الشهري التنافسي والسكن والسفر والتأمين الصحي."},
    "country": {"en": "United Arab Emirates", "ar": "الإمارات العربية المتحدة"},
    "university": {"en": "NYU Abu Dhabi", "ar": "جامعة نيويورك أبوظبي"},
    "degree": "PhD", "fundingType": "Fully Funded",
    "majors": ["Sciences", "Social Sciences", "Humanities", "Arts", "Engineering", "Economics"],
    "deadline": "2026-11-01",
    "link": "https://nyuad.nyu.edu/en/academics/graduate-programs.html",
    "image": "https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=800&auto=format&fit=crop",
    "keywords": ["UAE", "NYU", "Abu Dhabi", "PhD", "Fully Funded", "Middle East", "International"],
    "status": "approved"
  },
  {
    "title": {"en": "Monash University Graduate Research Scholarship Australia", "ar": "منحة بحث الدراسات العليا في جامعة موناش أستراليا"},
    "description": {"en": "Monash University offers the Monash Graduate Scholarship MGS to international PhD and Master by Research students. The scholarship covers full tuition fees and provides a living allowance for the duration of the candidature.", "ar": "تقدم جامعة موناش منحة البحث للخريجين MGS للطلاب الدوليين في مرحلة الدكتوراه والماجستير بالبحث. تغطي الرسوم الكاملة وتوفر بدل المعيشة لمدة الدراسة."},
    "country": {"en": "Australia", "ar": "أستراليا"},
    "university": {"en": "Monash University", "ar": "جامعة موناش"},
    "degree": "PhD", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Engineering", "Medicine", "Science", "Business", "Arts"],
    "deadline": "2026-10-31",
    "link": "https://www.monash.edu/graduate-research/future-students/scholarship/monash-graduate-scholarship",
    "image": "https://images.unsplash.com/photo-1607637508049-5b69d6ef0a25?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Australia", "Monash", "PhD", "Fully Funded", "Research", "Australian"],
    "status": "approved"
  },
  {
    "title": {"en": "Joint Japan World Bank Graduate Scholarship Program", "ar": "برنامج منح اليابان والبنك الدولي للدراسات العليا"},
    "description": {"en": "The Joint Japan World Bank Graduate Scholarship Program provides development professionals from World Bank member countries a graduate degree in development topics at a partner university outside their home country. Full funding.", "ar": "يوفر البرنامج المشترك بين اليابان والبنك الدولي للمهنيين التنمويين من الدول الأعضاء فرصة متابعة درجة دراسات عليا في موضوعات التنمية. تمويل كامل."},
    "country": {"en": "Multiple Countries", "ar": "دول متعددة"},
    "university": {"en": "World Bank Partner Universities", "ar": "جامعات شريكة للبنك الدولي"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Development Economics", "Public Policy", "Health", "Agriculture", "Environment"],
    "deadline": "2027-04-30",
    "link": "https://www.worldbank.org/en/programs/scholarships",
    "image": "https://images.unsplash.com/photo-1534951009808-766178b47a4f?q=80&w=800&auto=format&fit=crop",
    "keywords": ["World Bank", "Japan", "Development", "Master", "Fully Funded", "International", "Policy"],
    "status": "approved"
  },
  {
    "title": {"en": "Helmut Schmidt Programme DAAD Germany", "ar": "برنامج هيلموت شميت DAAD ألمانيا"},
    "description": {"en": "The Helmut Schmidt Programme funded by DAAD supports young professionals in developing countries studying masters programs related to public administration development and good governance in Germany.", "ar": "يدعم برنامج هيلموت شميت الممول من DAAD المهنيين الشباب في الدول النامية الذين يدرسون برامج الماجستير المتعلقة بالإدارة العامة والحوكمة الرشيدة في ألمانيا."},
    "country": {"en": "Germany", "ar": "ألمانيا"},
    "university": {"en": "German Universities", "ar": "الجامعات الألمانية"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Public Administration", "Development Studies", "Political Science", "International Relations"],
    "deadline": "2026-09-30",
    "link": "https://www.daad.de/en/study-and-research-in-germany/scholarships/helmut-schmidt-programme/",
    "image": "https://images.unsplash.com/photo-1577415124269-fc1140815932?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Germany", "DAAD", "Helmut Schmidt", "Master", "Fully Funded", "Public Administration", "Governance"],
    "status": "approved"
  },
  {
    "title": {"en": "Russian Government Scholarship International Students", "ar": "منحة الحكومة الروسية للطلاب الدوليين"},
    "description": {"en": "The Russian Government Scholarship offers international students opportunities to study at leading Russian universities. Covers tuition fees and provides a monthly stipend for masters bachelors and PhD programs.", "ar": "تقدم منحة الحكومة الروسية للطلاب الدوليين فرصاً للدراسة في الجامعات الروسية الرائدة. تغطي الرسوم الدراسية وتوفر راتباً شهرياً للماجستير والبكالوريوس والدكتوراه."},
    "country": {"en": "Russia", "ar": "روسيا"},
    "university": {"en": "Russian Universities", "ar": "الجامعات الروسية"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Engineering", "Sciences", "Arts", "Humanities", "Medicine"],
    "deadline": "2027-04-15",
    "link": "https://education-in-russia.com/",
    "image": "https://images.unsplash.com/photo-1548448396-b10e11ff7f44?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Russia", "Russian", "Government", "Master", "Bachelor", "PhD", "Fully Funded"],
    "status": "approved"
  },
  {
    "title": {"en": "Danish Government Scholarship Non-EU International Students", "ar": "منحة الحكومة الدنماركية للطلاب الدوليين"},
    "description": {"en": "The Danish Government offers scholarships to outstanding non-EU students enrolled in Masters degree programmes at Danish universities. Covers full tuition fees and may include a monthly stipend for living expenses.", "ar": "تقدم الحكومة الدنماركية منحاً دراسية للطلاب المتميزين من خارج الاتحاد الأوروبي الملتحقين ببرامج الماجستير في الجامعات الدنماركية. تغطي الرسوم الكاملة وقد تشمل راتباً شهرياً."},
    "country": {"en": "Denmark", "ar": "الدنمارك"},
    "university": {"en": "Danish Universities DTU Copenhagen Aarhus", "ar": "الجامعات الدنماركية DTU وكوبنهاغن وآرهوس"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Engineering", "IT", "Business", "Design", "Science"],
    "deadline": "2027-01-15",
    "link": "https://www.studyindenmark.dk/study-in-denmark/scholarship-in-denmark",
    "image": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Denmark", "Danish", "Scandinavia", "Master", "Fully Funded", "Nordic", "Copenhagen"],
    "status": "approved"
  },
  {
    "title": {"en": "University of Toronto Graduate Excellence Scholarship", "ar": "منحة التميز للدراسات العليا في جامعة تورنتو"},
    "description": {"en": "The University of Toronto School of Graduate Studies offers Excellence Awards to outstanding international graduate students in a wide range of disciplines with tuition coverage and a living stipend.", "ar": "تقدم كلية الدراسات العليا في جامعة تورنتو جوائز التميز للطلاب الدوليين المتميزين في مجموعة واسعة من التخصصات مع تغطية الرسوم وراتب المعيشة."},
    "country": {"en": "Canada", "ar": "كندا"},
    "university": {"en": "University of Toronto", "ar": "جامعة تورنتو"},
    "degree": "PhD", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Arts", "Science", "Engineering", "Law", "Medicine"],
    "deadline": "2027-01-06",
    "link": "https://www.sgs.utoronto.ca/awards/",
    "image": "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Canada", "Toronto", "Canadian", "PhD", "Fully Funded", "Excellence"],
    "status": "approved"
  },
  {
    "title": {"en": "Sciences Po Emile Boutmy Scholarship Paris France", "ar": "منحة إيميل بوتمي في Sciences Po باريس"},
    "description": {"en": "Sciences Po offers the Emile Boutmy Scholarship to exceptional international candidates from outside the European Economic Area for bachelor masters and PhD programs at Sciences Po Paris one of Europe leading institutions.", "ar": "تقدم Sciences Po منحة إيميل بوتمي للمرشحين الدوليين الاستثنائيين من خارج المنطقة الاقتصادية الأوروبية لبرامج البكالوريوس والماجستير والدكتوراه في Sciences Po باريس."},
    "country": {"en": "France", "ar": "فرنسا"},
    "university": {"en": "Sciences Po Paris", "ar": "Sciences Po باريس"},
    "degree": "Master", "fundingType": "Partially Funded",
    "majors": ["Political Science", "International Affairs", "Economics", "Sociology", "Law", "History"],
    "deadline": "2027-01-25",
    "link": "https://www.sciencespo.fr/admissions/en/content/emile-boutmy-scholarship.html",
    "image": "https://images.unsplash.com/photo-1551836022-deb4988cc6c0?q=80&w=800&auto=format&fit=crop",
    "keywords": ["France", "Sciences Po", "Paris", "Boutmy", "Master", "Social Sciences", "Political Science"],
    "status": "approved"
  },
  {
    "title": {"en": "KU Leuven University International Scholarship Belgium", "ar": "منحة جامعة KU لوفان الدولية بلجيكا"},
    "description": {"en": "KU Leuven Belgiums largest university offers scholarships for outstanding international students pursuing masters or doctoral degrees. Covers tuition fees and living expenses. Consistently ranked in the global top 50 universities.", "ar": "تقدم KU لوفان أكبر جامعة في بلجيكا منحاً للطلاب الدوليين المتميزين الذين يتابعون الماجستير أو الدكتوراه. تغطي الرسوم الدراسية ونفقات المعيشة."},
    "country": {"en": "Belgium", "ar": "بلجيكا"},
    "university": {"en": "KU Leuven", "ar": "جامعة KU لوفان"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Medicine", "Engineering", "Sciences", "Humanities", "Business"],
    "deadline": "2027-02-01",
    "link": "https://www.kuleuven.be/english/admissions/international-students/master-students/scholarships",
    "image": "https://images.unsplash.com/photo-1569963619402-cbfde80e7c78?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Belgium", "KU Leuven", "Belgian", "Master", "PhD", "Fully Funded", "Europe", "Research"],
    "status": "approved"
  },
  {
    "title": {"en": "ADB Japan Scholarship Program Asia Pacific", "ar": "برنامج منح بنك التنمية الآسيوي واليابان"},
    "description": {"en": "The ADB-Japan Scholarship Program JSP provides scholarships for citizens of ADB developing member countries to pursue postgraduate studies at designated institutions in the Asia and Pacific region funded by the Government of Japan.", "ar": "يوفر برنامج منح بنك التنمية الآسيوي واليابان JSP منحاً لمواطني الدول الأعضاء النامية لمتابعة الدراسات العليا في المؤسسات المعيّنة في منطقة آسيا والمحيط الهادئ."},
    "country": {"en": "Asia Pacific Region", "ar": "منطقة آسيا والمحيط الهادئ"},
    "university": {"en": "ADB Designated Institutions", "ar": "المؤسسات المعيّنة من قبل ADB"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Economics", "Business", "Development", "Engineering", "Environment", "Public Policy"],
    "deadline": "2027-04-30",
    "link": "https://www.adb.org/site/careers/japan-scholarship-program",
    "image": "https://images.unsplash.com/photo-1551503766-ac63dfa6401c?q=80&w=800&auto=format&fit=crop",
    "keywords": ["ADB", "Japan", "Asia Pacific", "Master", "Fully Funded", "Development", "Economics"],
    "status": "approved"
  },
  {
    "title": {"en": "Heinrich Boell Foundation Scholarship Germany Sustainability", "ar": "منحة مؤسسة هاينريش بول ألمانيا الاستدامة"},
    "description": {"en": "The Heinrich Boell Foundation supports international students for graduate or doctoral studies in Germany with a focus on ecology and sustainability. Covers monthly stipend health insurance social allowance and study expenses.", "ar": "تدعم مؤسسة هاينريش بول الطلاب الدوليين لمتابعة الدراسات العليا أو الدكتوراه في ألمانيا مع التركيز على البيئة والاستدامة. تغطي الراتب الشهري والتأمين الصحي ومصروفات الدراسة."},
    "country": {"en": "Germany", "ar": "ألمانيا"},
    "university": {"en": "German Universities", "ar": "الجامعات الألمانية"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Environmental Science", "Political Science", "Social Sciences", "Gender Studies", "Sustainability"],
    "deadline": "2027-03-01",
    "link": "https://www.boell.de/en/foundation/scholarships",
    "image": "https://images.unsplash.com/photo-1437491473895-c1e58cd9fe4e?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Germany", "Heinrich Boell", "Green", "Master", "PhD", "Fully Funded", "Ecology", "Sustainability"],
    "status": "approved"
  },
  {
    "title": {"en": "Konrad Adenauer Foundation Scholarship KAS Germany", "ar": "منحة مؤسسة كونراد أديناور KAS ألمانيا"},
    "description": {"en": "The Konrad Adenauer Foundation KAS awards scholarships to excellent students from abroad for studies and research in Germany promoting young talents who want to contribute to democracy and free social order.", "ar": "تمنح مؤسسة كونراد أديناور KAS منحاً دراسية للطلاب المتميزين من الخارج للدراسة والبحث في ألمانيا وتروّج للمواهب الشابة الراغبة في الإسهام في الديمقراطية."},
    "country": {"en": "Germany", "ar": "ألمانيا"},
    "university": {"en": "German Universities", "ar": "الجامعات الألمانية"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["Political Science", "Law", "Economics", "Social Sciences", "Theology"],
    "deadline": "2027-01-15",
    "link": "https://www.kas.de/en/web/begabtenfoerderung-und-kultur/scholarships",
    "image": "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Germany", "Konrad Adenauer", "KAS", "Master", "PhD", "Fully Funded", "Democracy", "Political"],
    "status": "approved"
  },
  {
    "title": {"en": "Czech Government Scholarship Programme Prague", "ar": "برنامج المنح الدراسية للحكومة التشيكية براغ"},
    "description": {"en": "The Czech Republic Ministry of Education offers scholarships for foreign nationals from developing countries to study at Czech public higher education institutions. Covers tuition fees living allowance and accommodation.", "ar": "تقدم وزارة التعليم التشيكية منحاً دراسية للمواطنين الأجانب من الدول النامية للدراسة في المؤسسات التشيكية العامة. تغطي الرسوم وبدل المعيشة والسكن."},
    "country": {"en": "Czech Republic", "ar": "جمهورية التشيك"},
    "university": {"en": "Czech Public Universities", "ar": "الجامعات العامة التشيكية"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Technical Sciences", "Agriculture", "Arts", "Natural Sciences"],
    "deadline": "2026-09-30",
    "link": "https://www.dzs.cz/en/programme/czech-government-scholarships/",
    "image": "https://images.unsplash.com/photo-1541849546-216549ae216d?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Czech", "Prague", "Central Europe", "Master", "Bachelor", "Fully Funded", "Government"],
    "status": "approved"
  },
  {
    "title": {"en": "New Zealand ASEAN Scholarship Program", "ar": "برنامج منحة نيوزيلندا لدول الآسيان"},
    "description": {"en": "New Zealand ASEAN Scholarships offered to citizens of ASEAN countries to study undergraduate and postgraduate programmes at New Zealand universities. Covers tuition living allowance travel and health insurance.", "ar": "تُقدَّم منح نيوزيلندا لمواطني دول الآسيان لدراسة برامج البكالوريوس والدراسات العليا في جامعات نيوزيلندا. تغطي الرسوم والمعيشة والسفر والتأمين الصحي."},
    "country": {"en": "New Zealand", "ar": "نيوزيلندا"},
    "university": {"en": "New Zealand Universities", "ar": "جامعات نيوزيلندا"},
    "degree": "Master", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Agriculture", "Technology", "Arts", "Sciences"],
    "deadline": "2026-09-01",
    "link": "https://www.studywithnewzealand.govt.nz/international-students/scholarships/nz-asean-leaders-scholarships",
    "image": "https://images.unsplash.com/photo-1589196728038-ecc4f48ee96d?q=80&w=800&auto=format&fit=crop",
    "keywords": ["New Zealand", "ASEAN", "Pacific", "Master", "Fully Funded", "Government"],
    "status": "approved"
  },
  {
    "title": {"en": "Ghent University Doctoral Fellowship DoFOE Belgium", "ar": "زمالة الدكتوراه للتنمية في جامعة غنت بلجيكا"},
    "description": {"en": "Ghent University offers the Doctoral fellowships for development DoFOE and masters scholarships to outstanding international students in biomedical sciences engineering agriculture and veterinary medicine.", "ar": "تقدم جامعة غنت زمالات الدكتوراه للتنمية DoFOE ومنح الماجستير للطلاب الدوليين المتميزين في العلوم الطبية الحيوية والهندسة والزراعة والطب البيطري."},
    "country": {"en": "Belgium", "ar": "بلجيكا"},
    "university": {"en": "Ghent University", "ar": "جامعة غنت"},
    "degree": "PhD", "fundingType": "Fully Funded",
    "majors": ["Biomedical Sciences", "Engineering", "Agriculture", "Veterinary Medicine", "Sciences"],
    "deadline": "2027-02-01",
    "link": "https://www.ugent.be/en/research/funding/bof/dofoe",
    "image": "https://images.unsplash.com/photo-1533929736458-ca588d08c8be?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Belgium", "Ghent", "Belgian", "PhD", "Fully Funded", "Research", "Europe"],
    "status": "approved"
  },
  {
    "title": {"en": "University of Manchester Presidents Doctoral Scholar Award UK", "ar": "جائزة رئيس جامعة مانشستر للدكتوراه المملكة المتحدة"},
    "description": {"en": "The University of Manchester Presidents Doctoral Scholar PDS Award provides full stipend tuition fees and a bursary for research. Open to international students of the highest academic ability in all disciplines.", "ar": "تكرّم جائزة رئيس جامعة مانشستر للدكتوراه PDS طلاب البحث المتميزين وتوفر راتباً كاملاً ورسوماً دراسية ومنحة للبحث. مفتوح للطلاب الدوليين."},
    "country": {"en": "United Kingdom", "ar": "المملكة المتحدة"},
    "university": {"en": "University of Manchester", "ar": "جامعة مانشستر"},
    "degree": "PhD", "fundingType": "Fully Funded",
    "majors": ["All Fields", "Engineering", "Sciences", "Business", "Arts", "Medicine"],
    "deadline": "2027-01-31",
    "link": "https://www.manchester.ac.uk/study/postgraduate-research/funding/president-doctoral-scholar-awards/",
    "image": "https://images.unsplash.com/photo-1610116306796-6fea9f4fae38?q=80&w=800&auto=format&fit=crop",
    "keywords": ["UK", "Manchester", "British", "PhD", "Fully Funded", "Research", "Doctoral"],
    "status": "approved"
  },
  {
    "title": {"en": "UCL Global Engagement Scholarship London UK", "ar": "منحة التواصل العالمي في UCL لندن"},
    "description": {"en": "UCL University College London offers Global Engagement Scholarships to students from underrepresented countries and regions. Supports the costs of studying a masters degree at UCL by covering tuition fees for eligible students.", "ar": "تقدم UCL جامعة كوليدج لندن منح التواصل العالمي للطلاب من الدول غير الممثلة. تدعم تكاليف دراسة الماجستير في UCL بتغطية الرسوم الدراسية للطلاب المؤهلين."},
    "country": {"en": "United Kingdom", "ar": "المملكة المتحدة"},
    "university": {"en": "University College London UCL", "ar": "جامعة كوليدج لندن UCL"},
    "degree": "Master", "fundingType": "Partially Funded",
    "majors": ["All Fields", "Arts", "Sciences", "Engineering", "Architecture", "Law"],
    "deadline": "2027-02-28",
    "link": "https://www.ucl.ac.uk/scholarships/",
    "image": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q=80&w=800&auto=format&fit=crop",
    "keywords": ["UK", "UCL", "London", "Master", "Partially Funded", "British", "International"],
    "status": "approved"
  },
  {
    "title": {"en": "Brunei Darussalam Government Scholarship UBD", "ar": "منحة حكومة بروناي دار السلام UBD"},
    "description": {"en": "Brunei Government Scholarships for international students at undergraduate and postgraduate levels at Universiti Brunei Darussalam UBD and other Brunei universities. Full funding including accommodation and living allowance.", "ar": "منح حكومة بروناي للطلاب الدوليين على مستوى البكالوريوس والدراسات العليا في جامعة بروناي UBD. تمويل كامل يشمل السكن وبدل المعيشة."},
    "country": {"en": "Brunei Darussalam", "ar": "بروناي دار السلام"},
    "university": {"en": "Universiti Brunei Darussalam UBD", "ar": "جامعة بروناي دار السلام UBD"},
    "degree": "Bachelor", "fundingType": "Fully Funded",
    "majors": ["Sciences", "Engineering", "Business", "Arts", "Law", "Islamic Studies"],
    "deadline": "2027-03-31",
    "link": "https://www.mfa.gov.bn/Pages/scholarship.aspx",
    "image": "https://images.unsplash.com/photo-1555992336-fb0d29498b13?q=80&w=800&auto=format&fit=crop",
    "keywords": ["Brunei", "ASEAN", "Southeast Asia", "Bachelor", "Master", "Fully Funded", "Government"],
    "status": "approved"
  }
]

# Write JSON
with open('scholarships_seed.json', 'w', encoding='utf-8') as f:
    json.dump(scholarships, f, ensure_ascii=False, indent=2)

# Write CSV
csv_fields = ['id', 'title_en', 'title_ar', 'description_en', 'description_ar', 'country_en', 'country_ar',
              'university_en', 'university_ar', 'degree', 'fundingType', 'majors', 'deadline', 'link', 'image', 'keywords', 'status']
with open('scholarships_seed.csv', 'w', newline='', encoding='utf-8-sig') as f:
    writer = csv.DictWriter(f, fieldnames=csv_fields)
    writer.writeheader()
    for i, s in enumerate(scholarships, 1):
        writer.writerow({
            'id': i,
            'title_en': s['title']['en'],
            'title_ar': s['title']['ar'],
            'description_en': s['description']['en'],
            'description_ar': s['description']['ar'],
            'country_en': s['country']['en'],
            'country_ar': s['country']['ar'],
            'university_en': s['university']['en'],
            'university_ar': s['university']['ar'],
            'degree': s['degree'],
            'fundingType': s['fundingType'],
            'majors': ' | '.join(s['majors']),
            'deadline': s['deadline'],
            'link': s['link'],
            'image': s['image'],
            'keywords': ' | '.join(s['keywords']),
            'status': s['status']
        })

print(f'Done! Written {len(scholarships)} scholarships to scholarships_seed.json and scholarships_seed.csv')
